import { describe, it, expect } from 'vitest';
import { stem } from '../stemmer.js';

describe('Porter Stemmer Module', () => {
  it('should handle words shorter than 3 characters by just lowercasing', () => {
    expect(stem('HE')).toBe('he');
    expect(stem('it')).toBe('it');
    expect(stem('an')).toBe('an');
    expect(stem('a')).toBe('a');
  });

  it('should validate against a large, representative list of Porter Stemmer test cases', () => {
    // 200+ word pairs from standard Porter stemmer vocabularies
    const wordPairs: [string, string][] = [
      // Step 1a: Plurals and Suffixes
      ['caresses', 'caress'],
      ['ponies', 'poni'],
      ['ties', 'ti'],
      ['caress', 'caress'],
      ['cats', 'cat'],
      ['dogs', 'dog'],
      ['classes', 'class'],
      ['indices', 'indic'],
      ['matrices', 'matric'],
      ['spies', 'spi'],
      ['cries', 'cri'],
      
      // Step 1b: -eed, -ed, -ing
      ['feed', 'feed'],
      ['agreed', 'agre'],
      ['plastered', 'plaster'],
      ['bled', 'bled'],
      ['motoring', 'motor'],
      ['sing', 'sing'],
      ['conflated', 'conflat'],
      ['troubled', 'troubl'],
      ['sized', 'size'],
      ['hopping', 'hop'],
      ['tanned', 'tan'],
      ['falling', 'fall'],
      ['hissing', 'hiss'],
      ['fizzing', 'fizz'],
      ['filing', 'file'],
      ['meeting', 'meet'],
      ['starting', 'start'],
      ['crying', 'cry'],
      
      // Step 1c: -y
      ['happy', 'happi'],
      ['sky', 'sky'],
      ['cry', 'cry'],
      ['baby', 'babi'],
      ['reply', 'repli'],
      ['worry', 'worri'],
      
      // Step 2: Double suffixes
      ['relational', 'relat'],
      ['conditional', 'condit'],
      ['rational', 'ration'],
      ['valency', 'valenc'],
      ['hesitancy', 'hesit'],
      ['digitizer', 'digit'],
      ['conformability', 'conform'],
      ['radically', 'radic'],
      ['differentli', 'differ'],
      ['vilely', 'vile'],
      ['analogously', 'analog'],
      ['vietnamization', 'vietnam'],
      ['predication', 'predic'],
      ['operator', 'oper'],
      ['feudalism', 'feudal'],
      ['decisiveness', 'decis'],
      ['hopefulness', 'hope'],
      ['callousness', 'callous'],
      ['formaliti', 'formal'],
      ['sensitiviti', 'sensit'],
      ['sensibiliti', 'sensibl'],
      ['nationalization', 'nation'],
      ['organizational', 'organiz'],
      
      // Step 3: -icate, -ative, -alize, -iciti, -ical, -ful, -ness
      ['triplicate', 'triplic'],
      ['formative', 'form'],
      ['formalize', 'formal'],
      ['electricity', 'electr'],
      ['electrical', 'electr'],
      ['hopeful', 'hope'],
      ['goodness', 'good'],
      ['definitiveness', 'definit'],
      ['illustrative', 'illustr'],
      
      // Step 4: -al, -ance, -ence, -er, -ic, -able, -ible, -ant, -ement, -ment, -ent, -ou, -ism, -ate, -iti, -ous, -ive, -ize, -ion
      ['revival', 'reviv'],
      ['allowance', 'allow'],
      ['inference', 'infer'],
      ['airliner', 'airlin'],
      ['gyroscopic', 'gyroscop'],
      ['adjustable', 'adjust'],
      ['defensible', 'defens'],
      ['irritant', 'irrit'],
      ['replacement', 'replac'],
      ['adjustment', 'adjust'],
      ['dependent', 'depend'],
      ['adoption', 'adopt'],
      ['homologou', 'homolog'],
      ['communism', 'commun'],
      ['activate', 'activ'],
      ['angulariti', 'angular'],
      ['homologous', 'homolog'],
      ['effective', 'effect'],
      ['bowdlerize', 'bowdler'],
      ['creation', 'creation'],
      ['destruction', 'destruct'],
      ['provision', 'provis'],
      
      // Step 5a: final -e
      ['probate', 'probat'],
      ['rate', 'rate'],
      ['cease', 'ceas'],
      ['hope', 'hope'],
      ['agree', 'agre'],
      
      // Step 5b: double -l
      ['controll', 'control'],
      ['roll', 'roll'],
      ['stall', 'stall'],
      ['distill', 'distil'],
      
      // Additional General Vocabulary
      ['computation', 'comput'],
      ['computational', 'comput'],
      ['computer', 'comput'],
      ['computers', 'comput'],
      ['computing', 'comput'],
      ['engineering', 'engin'],
      ['engineer', 'engin'],
      ['engineers', 'engin'],
      ['developing', 'develop'],
      ['developer', 'develop'],
      ['developers', 'develop'],
      ['development', 'develop'],
      ['normalize', 'normal'],
      ['normalizer', 'normal'],
      ['normalizes', 'normal'],
      ['normalized', 'normal'],
      ['tokenization', 'token'],
      ['tokenize', 'token'],
      ['tokenizer', 'token'],
      ['tokenizers', 'token'],
      ['tokenizing', 'token'],
      ['indexing', 'index'],
      ['indexer', 'index'],
      ['indexers', 'index'],
      ['indexes', 'index'],
      ['indexed', 'index'],
      ['searching', 'search'],
      ['searcher', 'searcher'],
      ['searched', 'search'],
      ['searches', 'search'],
      ['ranking', 'rank'],
      ['ranker', 'ranker'],
      ['ranked', 'rank'],
      ['ranks', 'rank'],
      ['queries', 'queri'],
      ['querying', 'queri'],
      ['crawling', 'crawl'],
      ['crawler', 'crawler'],
      ['crawlers', 'crawler'],
      ['crawls', 'crawl'],
      ['crawled', 'crawl'],
      ['accessibility', 'access'],
      ['accessible', 'access'],
      ['activity', 'activ'],
      ['agreement', 'agreement'],
      ['allowances', 'allow'],
      ['analyzing', 'analyz'],
      ['analyzed', 'analyz'],
      ['analyzer', 'analyz'],
      ['analyzers', 'analyz'],
      ['beautiful', 'beauti'],
      ['beautifully', 'beautifulli'],
      ['books', 'book'],
      ['booking', 'book'],
      ['booked', 'book'],
      ['capabilities', 'capabl'],
      ['capability', 'capabl'],
      ['comparative', 'compar'],
      ['comparison', 'comparison'],
      ['comparisons', 'comparison'],
      ['conclusions', 'conclus'],
      ['conclusive', 'conclus'],
      ['connecting', 'connect'],
      ['connected', 'connect'],
      ['connection', 'connect'],
      ['connections', 'connect'],
      ['constructive', 'construct'],
      ['construction', 'construct'],
      ['definitive', 'definit'],
      ['difficulty', 'difficulti'],
      ['difficulties', 'difficulti'],
      ['effectiveness', 'effect'],
      ['efficiency', 'effici'],
      ['efficient', 'effici'],
      ['efficiently', 'effici'],
      ['environments', 'environ'],
      ['environmental', 'environment'],
      ['exclusions', 'exclus'],
      ['exclusive', 'exclus'],
      ['expansion', 'expans'],
      ['generals', 'gener'],
      ['generalizations', 'gener'],
      ['generous', 'gener'],
      ['government', 'govern'],
      ['governments', 'govern'],
      ['governmental', 'government'],
      ['happiness', 'happi'],
      ['historical', 'histor'],
      ['history', 'histori'],
      ['histories', 'histori'],
      ['importance', 'import'],
      ['important', 'import'],
      ['importantly', 'importantli'],
      ['information', 'inform'],
      ['informative', 'inform'],
      ['initialization', 'initi'],
      ['initialize', 'initi'],
      ['initializers', 'initi'],
      ['iterations', 'iter'],
      ['iterative', 'iter'],
      ['keywords', 'keyword'],
      ['loading', 'load'],
      ['loaded', 'load'],
      ['loader', 'loader'],
      ['loaders', 'loader'],
      ['maintenance', 'mainten'],
      ['management', 'manag'],
      ['manager', 'manag'],
      ['managers', 'manag'],
      ['meaningful', 'meaning'],
      ['normalized', 'normal'],
      ['normalizing', 'normal'],
      ['operators', 'oper'],
      ['operation', 'oper'],
      ['operations', 'oper'],
      ['operational', 'oper'],
      ['pagination', 'pagin'],
      ['paginated', 'pagin'],
      ['performance', 'perform'],
      ['performances', 'perform'],
      ['positioning', 'posit'],
      ['positions', 'posit'],
      ['positional', 'posit'],
      ['processor', 'processor'],
      ['processors', 'processor'],
      ['processing', 'process'],
      ['processed', 'process'],
      ['proximity', 'proxim'],
      ['purgation', 'purgat'],
      ['purging', 'purg'],
      ['purged', 'purg'],
      ['reindexing', 'reindex'],
      ['reindexed', 'reindex'],
      ['retrieval', 'retriev'],
      ['retrieving', 'retriev'],
      ['retrieved', 'retriev'],
      ['scalability', 'scalabl'],
      ['scalable', 'scalabl'],
      ['scaffolded', 'scaffold'],
      ['scaffolding', 'scaffold'],
      ['scheduling', 'schedul'],
      ['scheduled', 'schedul'],
      ['scheduler', 'schedul'],
      ['schedulers', 'schedul'],
      ['scoring', 'score'],
      ['scored', 'score'],
      ['scores', 'score'],
      ['structuring', 'structur'],
      ['structured', 'structur'],
      ['structures', 'structur'],
      ['structural', 'structur'],
      ['suggestion', 'suggest'],
      ['suggestions', 'suggest'],
      ['suggestive', 'suggest'],
      ['synonyms', 'synonym'],
      ['testing', 'test'],
      ['tested', 'test'],
      ['testers', 'tester'],
      ['unindexed', 'unindex'],
      ['validation', 'valid'],
      ['validating', 'valid'],
      ['validated', 'valid'],
      ['verification', 'verif'],
      ['verifying', 'verifi'],
      ['verified', 'verifi']
    ];

    for (const [input, expected] of wordPairs) {
      const result = stem(input);
      expect(result).toBe(expected);
    }
  });
});
